version: "3.8"
services:
  cv:
    container_name: athena_cv
    build:
      context: ./docker/cv
      dockerfile: Dockerfile
    image: athena_cv
    volumes:
      - ./src:/var/src
  ml:
    container_name: athena_ml
    build:
      context: ./docker/ml
      dockerfile: Dockerfile
    image: athena_ml
    ports:
      - 8888:8888
    volumes:
      - ./notebooks:/var/notebooks